### ISSUE TITLE
code error?

### ISSUE THREAD

**Issue by lalalalala233333333** [aws-samples/aws-serverless-openai-chatbot-demo#1]
Hello,
I followed your above sequence and did it all the way down, but found that I couldn't log in successfully.
I suspect that there may be an error in the nodejs code, can you confirm it?

<img width="759" alt="image" src="https://user-images.githubusercontent.com/106228537/218103151-1dbe5963-654b-4bca-8e12-41a1b11cf49c.png">

**Comment by xiehust** [comment]
Hi, Did you check the request header in inspect mode of your browser? I guess one possible cause is that when you change the endpoint of api gateway of your own in the 1st line of  "apigw.js",  the last "/" has to be kept.

**Comment by lalalalala233333333** [comment]
Hi, Thanks! !
I did forget to put a "/" in the last line of "apigw.js".
After I added "/" to the end of the API Endpoint, I made a build under the "client" directory again ,and uploaded it to S3.
When I visit again, the error code becomes 500,underfined.
Is there anything else that could be wrong?

<img width="730" alt="image" src="https://user-images.githubusercontent.com/106228537/218117876-f105146b-a6b3-40c9-bee7-1602520f7040.png">

**Comment by lalalalala233333333** [comment]
I use nodejs16, I build on cloud9, and node16 is also used on cloud9.
The following is the log

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/106228537/218146970-f64c70a7-90c5-447d-9391-813c9d6c3cf5.png">

**Comment by xiehust** [comment]
I've seen that problem before, when changed to Nodejs 18, it resolved.   Or you might try "npm install @aws-sdk/client-dynamodb" under your existing environment.

**Comment by lalalalala233333333** [comment]
Thank you, I use nodejs16 on cloud9, I used the "npm install @aws-sdk/client-dynamodb" command to build the resources. Then re-upload to lambda (nodejs16). Then I saw the following error. I have assigned the role of the lambda the permission to access dynamodb. Is it because the account permissions I am using are not enough?

<img width="1018" alt="1" src="https://user-images.githubusercontent.com/106228537/218233467-7514ff49-1d4c-4299-8422-065aa6e9a787.png">

**Comment by xiehust** [comment]
yes ,I think so. it seems that the lambda does not have the permission to call GetItem from DynamoDb.  Did you add the DynamoDB read permission to the role of lambda_login function?

**Comment by lalalalala233333333** [comment]
grateful! I've solved accessing dynamodb permissions issue.
But when I tested again, I found that I encountered another 400 error.
I suspect something went wrong when I built it.
The following is the operation of the build I performed with nodejs16 on cloud9. Could you please help me to find out where is the problem?

1. lambda_login.zip
> cd server/lambda_login
> npm install @aws-sdk/client-dynamodb
> npm install
> zip -r lambda_login.zip .

2. Build the static files for client
> cd client
> npm install @aws-sdk/client-dynamodb
> npm install
> npm run build

If you switch to cloud9 and switch to nodejs18, will you still execute the above command?

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/106228537/218265542-f06f942a-7e7e-4955-a5e2-91fb835a4525.png">

**Comment by xiehust** [comment]
Hi, if you build for client, you don't need to install @aws-sdk, that is only for lambda login function. But I recommend you to using nodejs 18 for all, in that case, you do not need to install  aws-sdk at all. The lambda runtime has already included the aws sdk.
btw,i saw one person faced the same issue, then he changed nodejs 18, and it works now.

**Comment by lalalalala233333333** [comment]
After I switched to nodejs18 for build, I found that the same error still occurred.
Also could there be a problem?

error log:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/106228537/218291687-d7ca0fb0-2846-4c07-8f41-51f63a9f5c2d.png">


command:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/106228537/218291403-f9597e43-e1d9-47e6-a6c8-b07ac7f7f153.png">

lambda:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/106228537/218291581-ed880af3-ef3b-4921-bf36-8b6d3d36a789.png">

**Comment by xiehust** [comment]
the error seems like cannot get the item from the dynamodb table. did you check the table name and items (usename, password) are correctly configured？

**Comment by lalalalala233333333** [comment]
yes, I'm sure configure correctly the table name and items

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/106228537/218302365-3bd205fc-6313-4f7e-be12-41b691f1d4ad.png">

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/106228537/218302420-85a174d7-4ff6-4f2d-9a33-77b67466a246.png">

**Comment by xiehust** [comment]
which region are you using？ i put one line in the code to use default region of Tokyo. 
const DEFAULT_REGION = "ap-northeast-1"; you can change this to your actual region. And I will modify this restriction later.

**Comment by lalalalala233333333** [comment]
Thx!!!
I live in Tokyo, but I use the "us-east-1" for this test. :)

**Comment by lalalalala233333333** [comment]
Now It works!!!!!!!!!!!!!!!!
Thx!!!!!!!!!!!!!!!!!!

**Comment by xiehust** [comment]
Great, I am resolving this issue

**Comment by hill007** [comment]
@lalalalala233333333 Hello, did you encounter the 204 error when trying to access the login page after completing the setup?
