### ISSUE TITLE
chatGPT不是最新的版本？

### ISSUE THREAD

**Issue by hill007** [aws-samples/aws-serverless-openai-chatbot-demo#13]
搭建完成后发现，和chatgpt沟通，它的时间一致停留在2020年。这个需要哪里调整呢？
![图片](https://user-images.githubusercontent.com/54256063/220026031-a47af33e-95c4-4029-b4e9-e202b550a2c0.png)

**Comment by xiehust** [comment]
现在OpenAI公开的是gpt3.5模型的API，还不是最新的chatGPT模型，需要等将来OpenAI发布了ChatGPT的API后替换才行
