### ISSUE TITLE
This is incredible, and need help with this Step

### ISSUE THREAD

**Issue by dfrho** [aws-samples/aws-serverless-openai-chatbot-demo#14]
Thanks for this awesome repo. Tore through it up till here.
For Step 3 in the openai_chat function setup:

"...This function will invoke DynamoDB service API to verify the user credentials, so we need to attach AmazonDynamoDBReadOnlyAccess policy or create 
an inline policy to the role of this function."

I found the property in the docs by searching and it looks like you set this up in the console like so? Thanks very much!
<img width="1360" alt="Screen Shot 2023-02-20 at 7 53 55 PM" src="https://user-images.githubusercontent.com/3064557/220227826-173acdce-68df-4336-9ddd-2ee235213869.png">

**Comment by xiehust** [comment]
Hi,
DynamoDB access permission is required in lambda_login function. 
you can find the execution role here,
![image](https://user-images.githubusercontent.com/19160090/220228487-776b04fa-61a3-4006-a6d4-211683f0520a.png)
and then attach the pre-defined policy named AmazonDynamoDBReadOnlyAccess
![image](https://user-images.githubusercontent.com/19160090/220228519-0a66756f-107d-48ad-bd7b-3d5781b0afde.png)

**Comment by dfrho** [comment]
Got it thanks much!!
David

[image: ltp|16769458969521991]

**Comment by dfrho** [comment]
In the step 5 Set the CORS configuration as below:

I'm not following - put a giant X in each of the three fields?[image:
ltp|16769479109847630]

**Comment by dfrho** [comment]
<img width="808" alt="Screen Shot 2023-02-21 at 6 08 29 PM" src="https://user-images.githubusercontent.com/3064557/220487245-8bde6e0b-0b0e-470a-bbed-62123b7bbc83.png">

**Comment by dfrho** [comment]
Thanks
