### ISSUE TITLE
How to Set the CORS configuration

### ISSUE THREAD

**Issue by dfrho** [aws-samples/aws-serverless-openai-chatbot-demo#15]
In the step 5 Set the CORS configuration as below:

I'm not following - I doubt it means to put a giant X in each of the three fields, so how does one set the CORS config? Thanks very much.

<img width="808" alt="Screen Shot 2023-02-21 at 6 08 29 PM" src="https://user-images.githubusercontent.com/3064557/220487734-ddebe0c9-84d7-410d-a5ca-35513f33d544.png">

**Comment by xiehust** [comment]
Hi, it is to put a "*", which means "all" in each of those field.

**Comment by dfrho** [comment]
Thanks very much
