### ISSUE TITLE
JSON in bucket policy malformed

### ISSUE THREAD

**Issue by dfrho** [aws-samples/aws-serverless-openai-chatbot-demo#16]
Placing the cut and paste JSON into the S3 bucket policy results in a syntax error:
<img width="1134" alt="Screen Shot 2023-02-23 at 7 16 47 AM" src="https://user-images.githubusercontent.com/3064557/220917701-16150c57-9a62-4b9a-9779-9d1c9ca79898.png">

**Comment by xiehust** [comment]
My local text editor seems something goes wrong. Fixed now.  Remove the backslash.

**Comment by dfrho** [comment]
I tried removing the slash and still doesn't work:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/3064557/221178172-88dceefa-572a-4761-bfb3-1f6fde16bd74.png">
