### ISSUE TITLE
Reopening Closed Issue. 

### ISSUE THREAD

**Issue by dfrho** [aws-samples/aws-serverless-openai-chatbot-demo#19]
Earlier issue was closed without fixing. API Gateway after deploying still getting this auth error after removing the backslash in Principal property in bucket policy. Thanks for sticking with me on this.

`Access to fetch at 'https://3cncgd7ya0.execute-api.us-east-2.amazonaws.com/login' from origin 'http://bucket-name99.s3-website.us-east-2.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
POST https://3cncgd7ya0.execute-api.us-east-2.amazonaws.com/login net::ERR_FAILED 404`

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/3064557/221178252-a54642b7-6925-4f94-a46a-a8a4280b4af8.png">

**Comment by xiehust** [comment]
did you change the cors settings of api gateway?
![image](https://user-images.githubusercontent.com/19160090/221338324-980ddcad-64a6-4df2-9c86-5e8dd2f4f87f.png)

**Comment by dfrho** [comment]
yes, definitely.

**Comment by dfrho** [comment]
I'm noticing this linting error in the code but not sure how to fix it:

<img width="787" alt="Screen Shot 2023-02-25 at 7 59 26 AM" src="https://user-images.githubusercontent.com/3064557/221360990-97e4b2a6-489f-4ab5-890f-bd3e611856c9.png">

**Comment by xiehust** [comment]
This functon is invoked by AWS Lambda, which uses an async handler as default.   And the syntax of this file shoud be fine, it works in Lambda.
