### ISSUE TITLE
搭建完成了，但是无法登录

### ISSUE THREAD

**Issue by hill007** [aws-samples/aws-serverless-openai-chatbot-demo#2]
![图片](https://user-images.githubusercontent.com/54256063/218367746-256ed5bc-5964-4a15-856c-aa45a6657cbb.png)

**Comment by xiehust** [comment]
替换endpoint之后需要加"/'

**Comment by xiehust** [comment]
[client](https://github.com/aws-samples/aws-serverless-openai-chatbot-demo/tree/main/client)/[src](https://github.com/aws-samples/aws-serverless-openai-chatbot-demo/tree/main/client/src)/[commons](https://github.com/aws-samples/aws-serverless-openai-chatbot-demo/tree/main/client/src/commons)/apigw.js 在本地改这个文件的endpoint时，注意要保留最后一个'/'.
//Tips: don't miss the slash when you replace the endpoint url, or it will cause the bad request
const API_endpoint = 'https://xxxxxxx.amazonaws.com'+'/';

**Comment by hill007** [comment]
@xiehust

**Comment by hill007** [comment]
![图片](https://user-images.githubusercontent.com/54256063/218681358-d81b65a8-aa3b-41ee-9a63-d7076017da8a.png)
lambda函数报错

**Comment by xiehust** [comment]
看起来是网络请求里的url跟apigateway的url不一致。你再检查下js 代码里apigateway改正确了没有

**Comment by hill007** [comment]
核对了。是一致的。
![图片](https://user-images.githubusercontent.com/54256063/218699572-8e0dca3f-e6d7-4d23-856b-0a3e6bf5aadb.png)
![图片](https://user-images.githubusercontent.com/54256063/218699843-066fc1e5-bf72-4822-a14e-3af59d16e147.png)
我看apiGateway的日志报错如下：是不是nodejs的版本问题？
![图片](https://user-images.githubusercontent.com/54256063/218700938-40ea9493-1c3d-4829-a403-18e073208304.png)

**Comment by hill007** [comment]
@xiehust 您好，上面的问题解决了，参考您之前的回答，还是数据库的权限访问问题。但是发送消息后ai没有回复。
![图片](https://user-images.githubusercontent.com/54256063/218739402-0028d4fd-6440-4c0c-8920-3531c0ddce32.png)
查看后台日志提示这个，能否帮忙看看是什么原因？
![图片](https://user-images.githubusercontent.com/54256063/218739553-d1e8b923-5afd-4213-953f-131c1898be6c.png)
tks

**Comment by xiehust** [comment]
chat lambda函数没有call dynamoDB相关的东西，也没有安装aws-sdk module，怎么会显示这个错误，你检查下lambda的代码，是不是上传有误？

**Comment by hill007** [comment]
@xiehust 我检查了代码，重新从git 下载下来编译后还是一样。日志还是报错。
![图片](https://user-images.githubusercontent.com/54256063/218921174-568c7692-7c03-4ae9-bb9e-dfc62a91a367.png)
另外我看 lambda_login 函数  有引用。
![图片](https://user-images.githubusercontent.com/54256063/218921528-dcaeb80b-5293-4869-8bf2-c01fbf36012a.png)

**Comment by hill007** [comment]
按照提示，重新检查了一下代码。重新上传了上面的问题解决了。现在可以有回复了。但是如果遇到字符长的就会报错500
![图片](https://user-images.githubusercontent.com/54256063/218976371-441c2250-c267-41dd-a61d-cecff701b607.png)

**Comment by xiehust** [comment]
最近openai的接口很不稳定了，用的人太多了
