### ISSUE TITLE
V2版本不能选中文字用于复制

### ISSUE THREAD

**Issue by Bruce7988** [aws-samples/aws-serverless-openai-chatbot-demo#23]
我在手机上、电脑上打开了V2版本网页，发现在聊天界面不能选中文字。
用鼠标选中文字后，文字焦点马上消失，导致不能选中，无法复制。望解决。。

**Comment by xiehust** [comment]
可以用[v3](https://github.com/aws-samples/aws-serverless-openai-chatbot-demo/tree/main/v3-larkbot) 版本，集成到飞书bot，aws端支持cdk部署，可以用飞书个人版账号部署机器人。
