### ISSUE TITLE
v2聊天窗口经常出现 remote socket connection error

### ISSUE THREAD

**Issue by Bruce7988** [aws-samples/aws-serverless-openai-chatbot-demo#24]
如下图，聊天窗口经常出现 remote socket connection error
![图片](https://user-images.githubusercontent.com/2604278/222904448-4a93a01b-520e-48a3-89f3-3733b3a688b1.png)

**Comment by xiehust** [comment]
可能是你那边的网络不稳定，链接断开之后会自动重连。
