### ISSUE TITLE
Lark-ChatGptBot 部署成功后 会话不能连续提问，连续提问时机器人无法记住上一句

### ISSUE THREAD

**Issue by Bruce7988** [aws-samples/aws-serverless-openai-chatbot-demo#25]
如题，机器人无法记住上一句的问题
![图片](https://user-images.githubusercontent.com/2604278/223440520-23bd9ebb-48e0-4e1a-a8c4-eb6a398fc964.png)
请问如何解决？

**Comment by xiehust** [comment]
Thanks for pointing out this bug, I fixed now.please update your lambda function with the latest code of this [file](https://github.com/aws-samples/aws-serverless-openai-chatbot-demo/blob/main/v3-larkbot/cdkstack/lambda/handler_larkchat/index.js).
and you can change the maximum saved dialog by this value in the lambda_handlechat. 
![image](https://user-images.githubusercontent.com/19160090/224287529-fa62997f-cfa1-4340-a053-e2cb07031c26.png)

**Comment by Bruce7988** [comment]
@xiehust 
I changed the value of MAX_SEQ to 10 , as follows:

module.exports = __toCommonJS(handler_larkchat_exports);
var import_openai = require("openai");
var lark = __toESM(require("@larksuiteoapi/node-sdk"), 1);
var import_client_dynamodb = require("@aws-sdk/client-dynamodb");
**var MAX_SEQ = 10;**
var dbclient = new import_client_dynamodb.DynamoDBClient();
var start_command = process.env.START_CMD;
var larkclient = new lark.Client({
  appId: process.env.LARK_APPID,
  appSecret: process.env.LARK_APP_SECRET,
  appType: lark.AppType.SelfBuild
});

then I tried to chat , but nothing changed, the problem occured again
