### ISSUE TITLE
copy the chatbot message

### ISSUE THREAD

**Issue by SuperYanHD** [aws-samples/aws-serverless-openai-chatbot-demo#27]
when i select the message of chatbot result, that will renew the select item and change to select all item. so how can i copy the result?

i have to use v2-websocket

**Comment by SuperYanHD** [comment]
I edited the chatpage.jsx file by changing the values of reconnectAttempts and reconnectInterval to 4000 and 5000. This allows me ample time to receive messages.

**Comment by ciscogeek** [comment]
> when i select the message of chatbot result, that will renew the select item and change to select all item. so how can i copy the result?
> 
> i have to use v2-websocket

same issue.  How can I copy the chatbot messages?

**Comment by SuperYanHD** [comment]
> > when i select the message of chatbot result, that will renew the select item and change to select all item. so how can i copy the result?
> > i have to use v2-websocket
> 
> same issue. How can I copy the chatbot messages?

I edited the file "chatpage.jsx" located in client\src\pages\, and modified the values of reconnectAttempts and reconnectInterval to either 4000 and 5000 respectively, or 10000. After making the changes, I saved the file, "npm install" and "npm run build", and then sent it to s3.
