### ISSUE TITLE
503, {“message”：“Service Unavailable”}

### ISSUE THREAD

**Issue by picowithleo** [aws-samples/aws-serverless-openai-chatbot-demo#3]
有时候能正常回复有时候却出现503，是否是OpenAI 的接口的响应时间有关呢？已经调到3分钟了。

另外新增的Change model settings功能不清楚如何使用，会出现一堆重复的文字。
![ef052af579f1bba07b3204e75937b68](https://user-images.githubusercontent.com/58505907/218401444-31eaf80b-650d-49b5-aa46-de4c52aa8f2e.png)

**Comment by xiehust** [comment]
你看下lambda的日志，如果是时好时坏，那就是openai的api超时了，返回的503. 可能是openai现在访问的人太多了

**Comment by xiehust** [comment]
新架构升级，解决了大部分503超时问题。可以试试
[aws-serverless-openai-chatbot-demo](https://github.com/aws-samples/aws-serverless-openai-chatbot-demo)/v2-websocket/
