### ISSUE TITLE
sign in issue "Unexpected end of input" 

### ISSUE THREAD

**Issue by jtan0213** [aws-samples/aws-serverless-openai-chatbot-demo#32]
follow the guidance in [v2-websocket](https://github.com/aws-samples/aws-serverless-openai-chatbot-demo/tree/main/v2-websocket) readme file, but got this issue when login. 
<img width="860" alt="截屏2023-03-17 下午6 02 15" src="https://user-images.githubusercontent.com/101403771/225874362-f1358933-0346-4250-9695-3141d403705f.png">
<img width="781" alt="截屏2023-03-17 下午6 05 27" src="https://user-images.githubusercontent.com/101403771/225874921-9187dabd-dfce-4287-b267-6c7fb90f960d.png">

**Comment by SuperYanHD** [comment]
Try to IAW find DynamodDB connect to lambda_login

**Comment by jtan0213** [comment]
> Try to IAW find DynamodDB connect to lambda_login

solved. didn't config the CORS correctly, and also find the useful doc for  [·How to Create an AWS IAM Policy to Grant AWS Lambda Access to an Amazon DynamoDB Table·](https://aws.amazon.com/cn/blogs/security/how-to-create-an-aws-iam-policy-to-grant-aws-lambda-access-to-an-amazon-dynamodb-table/)
