### ISSUE TITLE
login完成后/chat返回500

### ISSUE THREAD

**Issue by windyzwj** [aws-samples/aws-serverless-openai-chatbot-demo#4]
login和auth似乎都是成功的，但是/chat会返回500，不知道是什么原因？本地nodejs是V16, lambda配置的v18会对/chat有影响吗？
<img width="432" alt="image" src="https://user-images.githubusercontent.com/122771510/218476193-fc64004d-f859-478a-a175-d3d653f0c509.png">
<img width="879" alt="image" src="https://user-images.githubusercontent.com/122771510/218476561-b470baea-d815-4418-bc38-4d7c60882456.png">

**Comment by xiehust** [comment]
你看看lambda的日志，是不是少了aws-sdk的module？ 都换成nodejs 18就没问题

**Comment by zyune** [comment]
我也有同样的问题

**Comment by zyune** [comment]
login和auth都是成功的. 但是到openai-chat 这个lambda function的log下面，什么都没显示。
<img width="1837" alt="Screen Shot 2023-02-14 at 8 09 43 PM" src="https://user-images.githubusercontent.com/66234261/218899196-0f529da8-f945-42c2-b719-7fc92b48d6ed.png">

**Comment by xiehust** [comment]
都换成node 18试试。

**Comment by ciscogeek** [comment]
> 你看看lambda的日志，是不是少了aws-sdk的module？ 都换成nodejs 18就没问题

宁夏和北京都没有 nodejs 18。我去其他区试试。

**Comment by zyune** [comment]
> 

是这样看吗？ 应该是有的吧？
<img width="938" alt="Screen Shot 2023-02-18 at 1 10 47 PM" src="https://user-images.githubusercontent.com/66234261/219881690-dde7ec91-26af-4090-8f7e-5567bb27ffa0.png">
现在能用了
