### ISSUE TITLE
 Error: 500,{"message":"Internal Server Error"}

### ISSUE THREAD

**Issue by zyune** [aws-samples/aws-serverless-openai-chatbot-demo#5]
每一步都按照要求配置后。报 500 error。
<img width="930" alt="Screen Shot 2023-02-14 at 8 15 47 PM" src="https://user-images.githubusercontent.com/66234261/218899866-b29ba971-ab0e-4eb3-8b77-e3a02a3de141.png">
去看了 aws Lambda的 chat-authorizer 和 openai-login都是有log的，但是openai-chat没有log。

**Comment by zyune** [comment]
Fixed. 在API Gateway中把chat-authorizer的Response mode 从I AM policy 改成了Simple
<img width="1335" alt="Screen Shot 2023-02-14 at 8 45 13 PM" src="https://user-images.githubusercontent.com/66234261/218906211-7545ba4c-0e26-483a-a98a-dfa499b0a67d.png">

**Comment by xiehust** [comment]
Good, I am resolving this

**Comment by hill007** [comment]
@zyune 能否把你的打包后的，三个函数程序。
    lambda_auth.zip
    lambda_login.zip
    lambda_chat.zip
  提供一下，我也遇到类似的问题。感谢。

**Comment by zyune** [comment]
> @zyune 能否把你的打包后的，三个函数程序。 lambda_auth.zip lambda_login.zip lambda_chat.zip 提供一下，我也遇到类似的问题。感谢。

Sure, what's your email address?
