### ISSUE TITLE
Ops! Error: 503,{"message":"Service Unavailable"}

### ISSUE THREAD

**Issue by ciscogeek** [aws-samples/aws-serverless-openai-chatbot-demo#9]
API GW 30秒超时，问题长了，都来不及回答。有解吗？

**Comment by xiehust** [comment]
有解的，后续会做个大的改动，改成ws接口，引入sns或者sqs异步处理，解决超时的问题。

**Comment by xiehust** [comment]
Hi, 
Please try this version: 
[aws-serverless-openai-chatbot-demo](https://github.com/aws-samples/aws-serverless-openai-chatbot-demo)/v2-websocket/
